name: typed_sql
publish_to: none
description: Package for doing SQL with some type safety.

environment:
  sdk: ^3.6.1

dependencies:
  meta: ^1.9.1
  collection: ^1.19.0
  sqlite3: ^2.7.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
