name: typed_sql
publish_to: none
description: Package for doing SQL with some type safety.

environment:
  sdk: ^3.6.1

dependencies:
  meta: ^1.9.1
  collection: ^1.19.0
  sqlite3: ^2.7.2
  build: ^2.2.2
  #build_config: ^1.0.0
  code_builder: ^4.2.0
  source_gen: ">=1.2.2 <3.0.0"
  analyzer: ^7.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.1.9
  build_verify: ^3.0.0
