name: neat_cache
on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/pkg-neat_cache-override.yml'
      - 'neat_cache/**'
  pull_request:
    paths:
      - '.github/workflows/pkg-neat_cache-override.yml'
      - 'neat_cache/**'
  schedule:
    - cron: "0 0 * * 0"

defaults:
  run:
    working-directory: neat_cache/

env:
  PUB_ENVIRONMENT: bot.github

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
         - stable
         - dev
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
      with:
        sdk: ${{ matrix.sdk }}
    - id: install
      name: Install dependencies
      run: dart pub get
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      if: always() && steps.install.outcome == 'success'
    - name: Analyze code
      run: dart analyze --fatal-infos
      if: always() && steps.install.outcome == 'success'
    - name: Run tests
      run: dart test
